version: '3.9'
services:
  simple-blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__Database=Host=db;Port=5432;Database=blog;Username=postgres;Password=postgres
    depends_on:
      - db
    command: sh -c "sleep 10 && dotnet simple-blog.dll"
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Infrastructure/Persistance/Database/Scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  db_data:
